name: DeepClustering_config
num_spks: 2
gpu: cuda:0
multi_gpu: False


train:
  mask_type: IBM
  epoch: 1000
  early_stop: 10
  path: ./checkpoint
  resume:
    state: False
    path: ./checkpoint/backups/data_augment_imbalance/best.pt

  optim:
    name: RMSprop
    lr: 1.0e-5
    momentum: 0.9
    weight_decay: 0
    clip_norm: 200

dataloader:
  batch_size: 20
  num_workers: 10
  shuffle: True

transform:
  n_fft: 256
  hop_length: 64
  win_length: 256
  window: 'hann'
  center: True
  sr: 8000
  mask_threshold : 40

network:
  hidden_size: 300
  num_layer: 2
  emb_D: 40
  dropout: 0.5
  bidirectional: True
  activation: Tanh
