name: DeepClustering_config
num_spks: 2
gpu: cuda:0
multi_gpu: False

# dir_wav_root: /data1/h_munakata/wsj0/2speakers/min/

dir_wav_root: /data1/h_munakata/test_data_augment/phone_phone/
# dir_wav_root: /data1/h_munakata/test_data_augment/phone_whitsle/
# dir_wav_root: /data1/h_munakata/test_data_augment/whitsle_whitsle/
# dir_wav_root: /data1/h_munakata/test_data_augment/wsj_phone/
# dir_wav_root: /data1/h_munakata/test_data_augment/wsj_whitsle/


# dir_wav_root: /data1/h_munakata/test_data_4_augment_speech
# dir_wav_root: /data1/h_munakata/data_augmentation/augment_block/

dataloader:
  train:
    path_scp_mix: ./scp/tr_mix.scp
    path_scp_targets: [./scp/tr_s1.scp,
                        ./scp/tr_s2.scp]
    mask: IBM

  val:
    path_scp_mix: ./scp/cv_mix.scp
    path_scp_targets: [./scp/cv_s1.scp,
                        ./scp/cv_s2.scp]
  batch_size: 20
  num_workers: 3
  shuffle: True

test:
  path_scp_mix: ./scp/tt_mix.scp
  path_scp_targets: [./scp/tt_s1.scp,
                    ./scp/tt_s2.scp]
  # path_model: ./checkpoint/backups/data_augment_imbalance/best.pt
  path_model: ./checkpoint/backups/data_augment_balance/best.pt
  # path_model: ./checkpoint/backups/data_augment_augmented/best.pt
  # path_model: ./checkpoint/backups/data_augment_removed/best.pt
  path_separated: ./result_test
  type_mask: hard
  eval_index: SI-SDR

transform:
  n_fft: 256
  hop_length: 64
  win_length: 256
  window: 'hann'
  center: True
  sr: 8000
  mask_threshold : 40

network:
  hidden_size: 300
  num_layer: 2
  emb_D: 40
  dropout: 0.5
  bidirectional: True
  activation: Tanh

train:
  epoch: 600
  early_stop: 10
  path: checkpoint
  is_gpu: True

optim:
  name: RMSprop
  lr: 1.0e-5
  momentum: 0.9
  weight_decay: 0
  clip_norm: 200

resume:
  state: False
  path: /home/h_munakata/DeepClustering_for_Speech_Separation/checkpoint/backups/data_augment_augmented/best.pt
